version: '3.4'

networks:
  backend:
    driver: bridge

volumes:
  sqlserver-data:
    driver: local

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04
    ports:
      - "1433:1433"
    networks:
      - backend
    volumes:
      - sqlserver-data:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "<YourStrong@Passw0rd>"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    networks:
      - backend
    depends_on:
      - db
    environment:
      - DOCKER_CONTAINER=true
  web:
    container_name: webContainer
    image: danielpalacios2003/urbantheater_front
    ports:
      - "9000:80"
    depends_on:
      - api
    networks:
      - backend
