apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: dotnetapp
spec:
  selector:
    app: dotnetapp
    tier: mssql
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      name: tcpsql
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: db
  labels:
    app: dotnetapp
spec:
  selector:
    matchLabels:
      app: dotnetapp
      tier: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dotnetapp
        tier: mssql
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      containers:
      - name: docker-compose-dotnet-core-and-mssql-db
        image: danielpalacios2003/urbantheater-db
        env:
        - name: MSSQL_PID
          value: "Express"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD 
