apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
        tier: frontend
    spec:
      containers:
      - name: api-net
<<<<<<< HEAD
        image: danielpalacios2003/apirds
=======
        image: danielpalacios2003/api11
>>>>>>> 749489358abb588cc6a36f20f112274e15a91dd2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
    - port: 80
  selector:
    app: api
    tier: frontend
  type: LoadBalancer
  

